// <auto-generated />
namespace Cinema_Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validtion4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validtion4));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251436572_validtion4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
